var ksa_compo = ksa_compo || {};
ksa_compo = {
		cust_infor:()=>{
			return '<div id="root">'
			+'		<div class="">'
			+'			<div id="checkVerifMethodModal"></div>'
			+'			<div id="QuoteOrderConfirmPopup"></div>'
			+'			<div class="">'
			+'				<div class="subMain">'
			+'					<section class="ty01">'
			+'						<article class="naviB">'
			+'							<h3>마이페이지</h3>'
			+'							<div class="listB">'
			+'								<ul>'
			+'									<li><a href="#" class="on">회원정보</a></li>'
			+'									<li><a href="#" class="">보안인증</a></li>'
			+'									<li><a href="#" class="">접속관리</a></li>'
			+'									<li><a href="#" class="">Open API 관리</a></li>'
			+'								</ul>'
			+'							</div>'
			+'						</article>'
			+'					</section>'
			+'					<div>'
			+'						<section id="right" class="ty02">'
			+'							<article>'
			+'								<div class="inforB">'
			+'									<h3>회원정보</h3>'
			+'									<div class="tableB">'
			+'										<table class="ty02">'
			+'											<colgroup>'
			+'												<col width="140">'
			+'												<col width="*">'
			+'											</colgroup>'
			+'											<tbody>'
			+'												<tr>'
			+'													<th>이메일</th>'
			+'													<td class="email"></td>'
			+'												</tr>'
			+'												<tr>'
			+'													<th>닉네임</th>'
			+'													<td><input type="text" class="txt03"'
			+'														placeholder="yakimdojin"><a href="#" class="btn">닉네임변경</a>'
			+'														<p>2~12자, 특수문자/띄어쓰기 불가, 닉네임은 변경 시점으로부터 6개월 뒤 변경 가능합니다.</p></td>'
			+'												</tr>'
			+'												<tr>'
			+'													<th>이름</th>'
			+'													<td class="ans">실명인증 필요</td>'
			+'												</tr>'
			+'												<tr class="last">'
			+'													<th>휴대폰</th>'
			+'													<td class="ans">실명인증 필요</td>'
			+'												</tr>'
			+'											</tbody>'
			+'										</table>'
			+'									</div>'
			+'									<div class="FullB">'
			+'										<h4>회원님의 현재 거래수수료</h4>'
			+'										<div class="tableB">'
			+'											<table class="ty02">'
			+'												<colgroup>'
			+'													<col width="25%">'
			+'													<col width="25%">'
			+'													<col width="25%">'
			+'													<col width="25%">'
			+'													<col width="*">'
			+'												</colgroup>'
			+'												<thead>'
			+'													<tr>'
			+'														<th>KRW 마켓</th>'
			+'														<th>BTC 마켓</th>'
			+'														<th>ETH 마켓</th>'
			+'														<th>USDT 마켓</th>'
			+'													</tr>'
			+'												</thead>'
			+'												<tbody>'
			+'													<tr>'
			+'														<td class="txt-center">0.05%</td>'
			+'														<td class="txt-center">0.25%</td>'
			+'														<td class="txt-center">0.25%</td>'
			+'														<td class="txt-center">0.25%</td>'
			+'													</tr>'
			+'												</tbody>'
			+'											</table>'
			+'											<p>※ 페이백 할인이 진행 중인 경우, 화면에 표시된 거래수수료를 선 수취 후 할인 금액만큼을 회원님'
			+'												계정으로 입금해 드립니다.</p>'
			+'											<a class="btnTxt" title="안내" href="/service_center/guide">거래수수료(부가세'
			+'												포함) 상세 안내 &gt;</a>'
			+'										</div>'
			+'									</div>'
			+'									<div class="agreeC">'
			+'										<h4>이용 동의 설정</h4>'
			+'										<div class="tableB">'
			+'											<table class="ty02">'
			+'												<colgroup>'
			+'													<col width="200">'
			+'													<col width="*">'
			+'												</colgroup>'
			+'												<tbody>'
			+'													<tr>'
			+'														<th>이벤트 등 안내(SMS,이메일) 수신동의</th>'
			+'														<td id="event_ok" class="rdo"><div>'
			+'																<a class="bgNone on"><em>-</em>동의</a>'
			+'																<a class="bgNone"><em>-</em>미동의</a>'
			+'															</div>'
			+'															<div>'
			+'																<span class="clearT">※ 입출금 안내 등 중요한 고지사항은 이벤트 안내'
			+'																	수신 동의 여부와 관계없이 이메일로 발송됩니다.</span>'
			+'															</div></td>'
			+'													</tr>'
			+'													<tr>'
			+'														<th>개인정보 제3자 제공 동의</th>'
			+'														<td id="info_ok" class="rdo"><div>'
			+'																<a class="bgNone"><em>-</em>동의</a><a '
			+'																	class="bgNone on"><em>-</em>미동의</a>'
			+'															</div>'
			+'															<div>'
			+'																<h5>제휴사인 Bittrex에 제공되며, 정보제공 동의 이후에 BTC/ETH/USDT 마켓'
			+'																	거래를 할 수 있습니다.</h5>'
			+'																<span class="marginT">※ 개인정보 제3자 제공 동의 해지 안내</span><span>개인정보'
			+'																	제3자 제공 동의를 해지하면 BTC/ETH/USDT 마켓 거래가 불가능합니다.</span>'
			+'															</div></td>'
			+'													</tr>'
			+'												</tbody>'
			+'											</table>'
			+'										</div>'
			+'										<a class="btnDrop" href="/mypage/customer_info/withdrawal">회원탈퇴</a>'
			+'									</div>'
			+'								</div>'
			+'							</article>'
			+'						</section>'
			+'					</div>'
			+'				</div>'
			+'			</div>'
			+'		</div>'
			+'	</div>'
		},
		cust_info_navi:()=>{
			return 	'							<article>'
			+'								<div class="inforB">'
			+'									<h3>회원정보</h3>'
			+'									<div class="tableB">'
			+'										<table class="ty02">'
			+'											<colgroup>'
			+'												<col width="140">'
			+'												<col width="*">'
			+'											</colgroup>'
			+'											<tbody>'
			+'												<tr>'
			+'													<th>이메일</th>'
			+'													<td class="email"></td>'
			+'												</tr>'
			+'												<tr>'
			+'													<th>닉네임</th>'
			+'													<td><input type="text" class="txt03"'
			+'														placeholder="yakimdojin"><a href="#" class="btn">닉네임변경</a>'
			+'														<p>2~12자, 특수문자/띄어쓰기 불가, 닉네임은 변경 시점으로부터 6개월 뒤 변경 가능합니다.</p></td>'
			+'												</tr>'
			+'												<tr>'
			+'													<th>이름</th>'
			+'													<td class="ans">실명인증 필요</td>'
			+'												</tr>'
			+'												<tr class="last">'
			+'													<th>휴대폰</th>'
			+'													<td class="ans">실명인증 필요</td>'
			+'												</tr>'
			+'											</tbody>'
			+'										</table>'
			+'									</div>'
			+'									<div class="FullB">'
			+'										<h4>회원님의 현재 거래수수료</h4>'
			+'										<div class="tableB">'
			+'											<table class="ty02">'
			+'												<colgroup>'
			+'													<col width="25%">'
			+'													<col width="25%">'
			+'													<col width="25%">'
			+'													<col width="25%">'
			+'													<col width="*">'
			+'												</colgroup>'
			+'												<thead>'
			+'													<tr>'
			+'														<th>KRW 마켓</th>'
			+'														<th>BTC 마켓</th>'
			+'														<th>ETH 마켓</th>'
			+'														<th>USDT 마켓</th>'
			+'													</tr>'
			+'												</thead>'
			+'												<tbody>'
			+'													<tr>'
			+'														<td class="txt-center">0.05%</td>'
			+'														<td class="txt-center">0.25%</td>'
			+'														<td class="txt-center">0.25%</td>'
			+'														<td class="txt-center">0.25%</td>'
			+'													</tr>'
			+'												</tbody>'
			+'											</table>'
			+'											<p>※ 페이백 할인이 진행 중인 경우, 화면에 표시된 거래수수료를 선 수취 후 할인 금액만큼을 회원님'
			+'												계정으로 입금해 드립니다.</p>'
			+'											<a class="btnTxt" title="안내" href="/service_center/guide">거래수수료(부가세'
			+'												포함) 상세 안내 &gt;</a>'
			+'										</div>'
			+'									</div>'
			+'									<div class="agreeC">'
			+'										<h4>이용 동의 설정</h4>'
			+'										<div class="tableB">'
			+'											<table class="ty02">'
			+'												<colgroup>'
			+'													<col width="200">'
			+'													<col width="*">'
			+'												</colgroup>'
			+'												<tbody>'
			+'													<tr>'
			+'														<th>이벤트 등 안내(SMS,이메일) 수신동의</th>'
			+'														<td class="rdo"><div>'
			+'																<a class="bgNone on"><em>-</em>동의</a>'
			+'																<a class="bgNone"><em>-</em>미동의</a>'
			+'															</div>'
			+'															<div>'
			+'																<span class="clearT">※ 입출금 안내 등 중요한 고지사항은 이벤트 안내'
			+'																	수신 동의 여부와 관계없이 이메일로 발송됩니다.</span>'
			+'															</div></td>'
			+'													</tr>'
			+'													<tr>'
			+'														<th>개인정보 제3자 제공 동의</th>'
			+'														<td class="rdo"><div>'
			+'																<a class="bgNone"><em>-</em>동의</a><a '
			+'																	class="bgNone on"><em>-</em>미동의</a>'
			+'															</div>'
			+'															<div>'
			+'																<h5>제휴사인 Bittrex에 제공되며, 정보제공 동의 이후에 BTC/ETH/USDT 마켓'
			+'																	거래를 할 수 있습니다.</h5>'
			+'																<span class="marginT">※ 개인정보 제3자 제공 동의 해지 안내</span><span>개인정보'
			+'																	제3자 제공 동의를 해지하면 BTC/ETH/USDT 마켓 거래가 불가능합니다.</span>'
			+'															</div></td>'
			+'													</tr>'
			+'												</tbody>'
			+'											</table>'
			+'										</div>'
			+'										<a class="btnDrop" href="/mypage/customer_info/withdrawal">회원탈퇴</a>'
			+'									</div>'
			+'								</div>'
			+'							</article>'
		},
		cust_acc:()=>{
			return '						<article>'
			+'							<div class="inforB">'
			+'								<h3>접속관리</h3>'
			+'								<p class="txt incBtRight">'
			+'									회원님의 업비트 로그인 이력입니다. 직접 로그인하지 않은 기록이 있다면,<br>즉시 <a'
			+'										href="https://accounts.kakao.com/weblogin/find_password?continue=https://accounts.kakao.com/weblogin/account/info"'
			+'										target="_blank">카카오계정 비밀번호 변경</a> 및 모든 디바이스에서 로그아웃 해주세요.<a'
			+'										href="" class="LogoutBt">모든 디바이스에서 로그아웃</a>'
			+'								</p>'
			+'								<div class="tableB">'
			+'									<table class="ty01">'
			+'										<colgroup>'
			+'											<col width="*">'
			+'											<col width="195">'
			+'											<col width="200">'
			+'											<col width="125">'
			+'											<col width="165">'
			+'										</colgroup>'
			+'										<thead>'
			+'											<tr>'
			+'												<th>위치</th>'
			+'												<th>기종</th>'
			+'												<th>브라우저</th>'
			+'												<th>아이피</th>'
			+'												<th>일시</th>'
			+'											</tr>'
			+'										</thead>'
			+'										<tbody>'
			+'											<tr>'
			+'												<td class="lAlign">-</td>'
			+'												<td class="lAlign">Windows 6.1</td>'
			+'												<td class="lAlign">Chrome 73</td>'
			+'												<td>115.94.144.226</td>'
			+'												<td>2019.04.23 09:07:05</td>'
			+'											</tr>'
			+'											<tr>'
			+'												<td class="lAlign">-</td>'
			+'												<td class="lAlign">Windows 6.1</td>'
			+'												<td class="lAlign">Chrome 73</td>'
			+'												<td>115.94.144.226</td>'
			+'												<td>2019.04.22 17:52:57</td>'
			+'											</tr>'
			+'										</tbody>'
			+'									</table>'
			+'								</div>'
			+'							</div>'
			+'						</article>'
		},
		investment_coin:()=>{
			return '<div id="root">'
			+'		<div class="">'
			+'			<div id="checkVerifMethodModal"></div>'
			+'			<div id="QuoteOrderConfirmPopup"></div>'
			+'			<div class="">'
			+'				<div class="mainB">'
			+'					<section class="ty01">'
			+'    				<article>'
			+'        				<span class="tabB">'
			+'            				<ul class="top ty04">'
			+'                				<li><a class="on" title="보유코인">보유코인</a></li>'
			+'                				<li><a class="" title="거래내역">거래내역</a></li>'
			+'               				<li><a class="" title="미체결">미체결</a></li>'
			+'               				<li><a class="" title="입출금대기">입출금대기</a></li>'
			+'           				 </ul>'
			+'       				 </span>'
			+'        				 <span class="ownB">'
			+'            <div class="rMsg">'
			+'                <span>* 매수평균가, 평가금액, 평가손익, 수익률은 모두 <strong>KRW로 환산한 추정값으로 참고용</strong>입니다.</span>&nbsp;'
			+'                <a href="#" class="tooltipDown"><div style="width: 270px;">'
			+'                        <strong>[보유코인 유의사항]</strong>'
			+'                        <p class="bgNone">'
			+'                            <em>1.</em> 보유코인의 매수평균가, 평가금액, 평가손익, 수익률<br>은 모두 KRW로 환산한 추정값으로 참고용입니다.'
			+'                        </p>'
			+'                        <p>'
			+'                            업비트에서는 4가지의 기초화폐(KRW, BTC, ETH,<br>USDT)로 암호화폐를 거래할 수 있습니다.'
			+'                        </p>'
			+'                        <p>'
			+'                            4가지 기초화폐 중 어떤 것으로 거래하는가에 따라서<br>'
			+'                            매수가격의 단위가 달라지며, 하나의 코인을 2가지<br>'
			+'                            이상의 기초화폐로 거래하게 되면 현재 수익률을<br>'
			+'                            확인하는 것이 어려워지게 됩니다.'
			+'                        </p>'
			+'                        <p>'
			+'                            이를 위한 보완책으로 모든 가격의 단위를 KRW로<br>환산해 현재 추정 수익률을 참고용으로 확인하실 수<br>'
			+'                            있도록 제공합니다.'
			+'                        </p>'
			+'                        <p class="bgNone line">'
			+'                            <em>2.</em> 보유코인의 매수/매도 및 입금/출금 내역을 모두<br>'
			+'                            반영합니다. 입금 내역의 매수평균가는 입금 시점의<br>'
			+'                            시세를 반영해 계산합니다.'
			+'                        </p>'
			+'                        <p class="bgNone line">'
			+'                            <em>3.</em> 계산 방식'
			+'                        </p>'
			+'                        <p>총평가: 보유 암호화폐의 평가금액 합계</p>'
			+'                        <p>총 보유자산: 총평가 + 보유KRW</p>'
			+'                        <p>'
			+'                            매수평균가: 매수(입금) 체결 시 직전 매수평균가와<br>'
			+'                            평균, 매도(출금) 체결 시 직전 매수평균가 유지<br>'
			+'                            <span>&gt; BTC 마켓의 매수가격은 BTC/KRW 가격을 반영해<br>'
			+'                                KRW로 환산(같은 방식으로 ETH 마켓과 USDT 마켓<br>'
			+'                                가격도 KRW로 환산)'
			+'                            </span>'
			+'                        </p>'
			+'                        <p>매수금액: 보유수량 x 매수평균가</p>'
			+'                        <p>'
			+'                            평가금액: 보유수량 x 현재가<br>'
			+'                            <span>&gt; 보유코인이 KRW마켓에 상장되어 있으면 KRW<br>'
			+'                                마켓 현재가 기준, 그렇지 않으면 BTC 마켓의 현재가<br>'
			+'                                를 KRW로 환산해서 평가금액 계산'
			+'                            </span>'
			+'                        </p>'
			+'                        <p>평가손익: 평가금액 – 매수금액</p>'
			+'                        <p>수익률: 평가손익 ÷ 매수금액</p>'
			+'                        <p class="bgNone line">'
			+'                            <em>※</em> 보유코인을 어떤 마켓에서 매매한 것인지에 따라서,<br>'
			+'                            혹은 입출금이 빈번이 발생하는 경우 수익률이 과대<br>'
			+'                            혹은 과소평가되어 보일 수 있습니다. (고객님의 보유<br>'
			+'                            수량에는 영향을 미치지 않습니다.)<br>'
			+'                            <span>이는 고객님의 수익평가에 대한 참고자료로, 업비트는<br>'
			+'                                제공된 편의정보를 기반으로한 투자결과에 대한<br>'
			+'                                책임을 지지 않습니다.'
			+'                            </span>'
			+'                        </p>'
			+'                    </div>'
			+'                </a>'
			+'            </div>'
			+'            <div class="acctB" style="padding-top:1px;">'
			+'                <div id="total_price" class="box01" style="padding: 0 30px 0 30px; width: 330px;">'
			+'                    <span><em>총매수금액</em><strong>0 <i>KRW</i></strong></span>'
			+'                    <span><em>총평가금액</em><strong>0 <i>KRW</i></strong></span>'
			+'                </div>'
			+'                <div id="evaluation" class="box01" style="padding: 0 30px 0 30px; width: 330px;">'
			+'                    <span><em>총평가손익</em><strong class="">0 <i>KRW</i></strong></span>'
			+'                    <span><em>총평가수익률</em><strong class="">0 <i>%</i></strong></span>'
			+'                </div>'
			+'                <div id="assets" class="box01" style="padding: 0 30px 0 30px; width: 330px;">'
			+'                    <span><em>보유 KRW</em><strong>0 <i>KRW</i></strong></span>'
			+'                    <span><em>총 보유자산</em><strong>0 <i>KRW</i></strong></span>'
			+'                </div>'
			+'            </div>'
			+'            <table class="ty03">'
			+'                <colgroup>'
			+'                    <col width="*">'
			+'                    <col width="*">'
			+'                    <col width="*">'
			+'                    <col width="*">'
			+'                    <col width="*">'
			+'                </colgroup>'
			+'                <thead>'
			+'                    <tr>'
			+'                        <th style="text-align:center;">보유코인</th>'
			+'                        <th style="text-align:center;">보유수량</th>'
			+'                        <th style="text-align:center;">매수금액 </th>'
			+'                        <th style="text-align:center;">평가금액 </th>'
			+'                        <th style="text-align:center;">평가손익(%)</th>'
			+'                    </tr>'
			+'                </thead>'
			+'            </table>'
			+'            <div style="position: relative; overflow: hidden; width: 100%; height: 647px;">'
			+'                <div style="position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; overflow: scroll; margin-right: -17px; margin-bottom: -17px;">'
			+'                    <table class="ty03">'
			+'                        <colgroup>'
			+'                            <col width="*">'
			+'                            <col width="*">'
			+'                            <col width="*">'
			+'                            <col width="*">'
			+'                            <col width="*">'
			+'                        </colgroup>'
			+'                        <tbody>'
			+'                            <tr id="hcoin">'
			+'                                <th>'
			+'                                    <em class="logo" style="background: url(&quot;/web/resources/img/logo3.png&quot;) 0px 0px / cover no-repeat;">-</em>'
			+'                                    <a class="tit" style="text-decoration: none;"><strong>원스코인</strong><i>ONCE</i></a>'
			+'                                </th>'
			+'                                <td><strong>0 <i>BTC</i></strong></td>'
			+'                                <td><em>0 <i>KRW</i></em></td>'
			+'                                <td><em>0 <i>KRW</i></em></td>'
			+'                                <td><span><em class="">0 <i>%</i></em></span><span><em class="">0 <i>KRW</i></em></span></td>'
			+'                            </tr>'
			+'                        </tbody>'
			+'                    </table>'
			+'                </div>'
			+'                <div style="position: absolute; height: 6px; right: 2px; bottom: 2px; left: 2px; border-radius: 3px;">'
			+'                    <div style="position: relative; display: block; height: 100%; cursor: pointer; border-radius: inherit; background-color: rgba(0, 0, 0, 0.2); width: 0px;"></div>'
			+'                </div>'
			+'                <div style="position: absolute; width: 6px; right: 2px; bottom: 2px; top: 2px; border-radius: 3px;">'
			+'                    <div style="position: relative; display: block; width: 100%; cursor: pointer; border-radius: inherit; background-color: rgba(0, 0, 0, 0.2); height: 0px;"></div>'
			+'                </div>'
			+'            </div>'
			+'        </span>'
			+'    </article>'
			+'</section>'
			+'				</div>'
			+'			</div>'
			+'		</div>'
			+'	</div>'
		},
		investment_hcoin:()=>{
			return '        <span class="ownB">'
		    +'            <div class="rMsg">'
		    +'                <span>* 매수평균가, 평가금액, 평가손익, 수익률은 모두 <strong>KRW로 환산한 추정값으로 참고용</strong>입니다.</span>&nbsp;'
		    +'                <a href="#" class="tooltipDown"><div style="width: 270px;">'
		    +'                        <strong>[보유코인 유의사항]</strong>'
		    +'                        <p class="bgNone">'
		    +'                            <em>1.</em> 보유코인의 매수평균가, 평가금액, 평가손익, 수익률<br>은 모두 KRW로 환산한 추정값으로 참고용입니다.'
		    +'                        </p>'
		    +'                        <p>'
		    +'                            업비트에서는 4가지의 기초화폐(KRW, BTC, ETH,<br>USDT)로 암호화폐를 거래할 수 있습니다.'
		    +'                        </p>'
		    +'                        <p>'
		    +'                            4가지 기초화폐 중 어떤 것으로 거래하는가에 따라서<br>'
		    +'                            매수가격의 단위가 달라지며, 하나의 코인을 2가지<br>'
		    +'                            이상의 기초화폐로 거래하게 되면 현재 수익률을<br>'
		    +'                            확인하는 것이 어려워지게 됩니다.'
		    +'                        </p>'
		    +'                        <p>'
		    +'                            이를 위한 보완책으로 모든 가격의 단위를 KRW로<br>환산해 현재 추정 수익률을 참고용으로 확인하실 수<br>'
		    +'                            있도록 제공합니다.'
		    +'                        </p>'
		    +'                        <p class="bgNone line">'
		    +'                            <em>2.</em> 보유코인의 매수/매도 및 입금/출금 내역을 모두<br>'
		    +'                            반영합니다. 입금 내역의 매수평균가는 입금 시점의<br>'
		    +'                            시세를 반영해 계산합니다.'
		    +'                        </p>'
		    +'                        <p class="bgNone line">'
		    +'                            <em>3.</em> 계산 방식'
		    +'                        </p>'
		    +'                        <p>총평가: 보유 암호화폐의 평가금액 합계</p>'
		    +'                        <p>총 보유자산: 총평가 + 보유KRW</p>'
		    +'                        <p>'
		    +'                            매수평균가: 매수(입금) 체결 시 직전 매수평균가와<br>'
		    +'                            평균, 매도(출금) 체결 시 직전 매수평균가 유지<br>'
		    +'                            <span>&gt; BTC 마켓의 매수가격은 BTC/KRW 가격을 반영해<br>'
		    +'                                KRW로 환산(같은 방식으로 ETH 마켓과 USDT 마켓<br>'
		    +'                                가격도 KRW로 환산)'
		    +'                            </span>'
		    +'                        </p>'
		    +'                        <p>매수금액: 보유수량 x 매수평균가</p>'
		    +'                        <p>'
		    +'                            평가금액: 보유수량 x 현재가<br>'
		    +'                            <span>&gt; 보유코인이 KRW마켓에 상장되어 있으면 KRW<br>'
		    +'                                마켓 현재가 기준, 그렇지 않으면 BTC 마켓의 현재가<br>'
		    +'                                를 KRW로 환산해서 평가금액 계산'
		    +'                            </span>'
		    +'                        </p>'
		    +'                        <p>평가손익: 평가금액 – 매수금액</p>'
		    +'                        <p>수익률: 평가손익 ÷ 매수금액</p>'
		    +'                        <p class="bgNone line">'
		    +'                            <em>※</em> 보유코인을 어떤 마켓에서 매매한 것인지에 따라서,<br>'
		    +'                            혹은 입출금이 빈번이 발생하는 경우 수익률이 과대<br>'
		    +'                            혹은 과소평가되어 보일 수 있습니다. (고객님의 보유<br>'
		    +'                            수량에는 영향을 미치지 않습니다.)<br>'
		    +'                            <span>이는 고객님의 수익평가에 대한 참고자료로, 업비트는<br>'
		    +'                                제공된 편의정보를 기반으로한 투자결과에 대한<br>'
		    +'                                책임을 지지 않습니다.'
		    +'                            </span>'
		    +'                        </p>'
		    +'                    </div>'
		    +'                </a>'
		    +'            </div>'
		    +'            <div class="acctB" style="padding-top:1px;">'
		    +'                <div id="total_price" class="box01" style="padding: 0 30px 0 30px; width: 330px;">'
		    +'                    <span><em>총매수금액</em><strong>0 <i>KRW</i></strong></span>'
		    +'                    <span><em>총평가금액</em><strong>0 <i>KRW</i></strong></span>'
		    +'                </div>'
		    +'                <div id="evaluation" class="box01" style="padding: 0 30px 0 30px; width: 330px;">'
		    +'                    <span><em>총평가손익</em><strong class="">0 <i>KRW</i></strong></span>'
		    +'                    <span><em>총평가수익률</em><strong class="">0 <i>%</i></strong></span>'
		    +'                </div>'
		    +'                <div id="assets" class="box01" style="padding: 0 30px 0 30px; width: 330px;">'
		    +'                    <span><em>보유 KRW</em><strong>0 <i>KRW</i></strong></span>'
		    +'                    <span><em>총보유자산</em><strong>0 <i>KRW</i></strong></span>'
		    +'                </div>'
		    +'            </div>'
		    +'            <table class="ty03">'
		    +'                <colgroup>'
		    +'                    <col width="*">'
		    +'                    <col width="*">'
		    +'                    <col width="*">'
		    +'                    <col width="*">'
		    +'                    <col width="*">'
		    +'                </colgroup>'
		    +'                <thead>'
		    +'                    <tr>'
		    +'                        <th style="text-align:center;">보유코인</th>'
		    +'                        <th style="text-align:center;">보유수량</th>'
		    +'                        <th style="text-align:center;">매수금액</th>'
		    +'                        <th style="text-align:center;">평가금액</th>'
		    +'                        <th style="text-align:center;">평가손익(%)</th>'
		    +'                    </tr>'
		    +'                </thead>'
		    +'            </table>'
		    +'            <div style="position: relative; overflow: hidden; width: 100%; height: 647px;">'
		    +'                <div style="position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; overflow: scroll; margin-right: -17px; margin-bottom: -17px;">'
		    +'                    <table class="ty03">'
		    +'                        <colgroup>'
		    +'                            <col width="*">'
		    +'                            <col width="*">'
		    +'                            <col width="*">'
		    +'                            <col width="*">'
		    +'                            <col width="*">'
		    +'                        </colgroup>'
		    +'                        <tbody>'
		    +'                            <tr id="hcoin">'
		    +'                                <th>'
		    +'                                    <em class="logo" style="background: url(&quot;/web/resources/img/logo3.png&quot;) 0px 0px / cover no-repeat;">-</em>'
		    +'                                    <a class="tit" style="text-decoration: none;"><strong>원스코인</strong><i>ONCE</i></a>'
		    +'                                </th>'
		    +'                                <td><strong>0 <i>ONCE</i></strong></td>'
		    +'                                <td><em>0 <i>KRW</i></em></td>'
		    +'                                <td><em>0 <i>KRW</i></em></td>'
		    +'                                <td><span><em class="">0 <i>%</i></em></span><span><em class="">0 <i>KRW</i></em></span></td>'
		    +'                            </tr>'
		    +'                        </tbody>'
		    +'                    </table>'
		    +'                </div>'
		    +'                <div style="position: absolute; height: 6px; right: 2px; bottom: 2px; left: 2px; border-radius: 3px;">'
		    +'                    <div style="position: relative; display: block; height: 100%; cursor: pointer; border-radius: inherit; background-color: rgba(0, 0, 0, 0.2); width: 0px;"></div>'
		    +'                </div>'
		    +'                <div style="position: absolute; width: 6px; right: 2px; bottom: 2px; top: 2px; border-radius: 3px;">'
		    +'                    <div style="position: relative; display: block; width: 100%; cursor: pointer; border-radius: inherit; background-color: rgba(0, 0, 0, 0.2); height: 0px;"></div>'
		    +'                </div>'
		    +'            </div>'
		    +'        </span>'
		},
		investment_trx:()=>{
			return '<center>'
			+'        <div class="profitW">'
			+'            <div class="proSearch">'
			+'                <select id="proSearch">'
			+'                    <option value="allType">거래 전체</option>'
			+'                    <option value="bid">매수</option>'
			+'                    <option value="ask">매도</option>'
			+'                    <option value="deposit">입금</option>'
			+'                </select>'
			+'            </div>'
			+'            <table class="ty04" style="margin-left: auto; margin-right: auto;">'
			+'                <thead>'
			+'                    <tr>'
			+'                        <th style="text-align:center;">주문시간</th>'
			+'                        <th style="text-align:center;">거래종류</th>'
			+'                        <th style="text-align:center;">거래수량</th>'
			+'                        <th style="text-align:center;">거래단가</th>'
			+'                        <th style="text-align:center;">거래금액</th>'
			+'                    </tr>'
			+'                </thead>'
			+'            </table>'
			+'            <div class="scrollB" style="height: 720px;">'
			+'                <div style="position: relative; overflow: hidden; width: 100%; height: 720px;">'
			+'                    <div style="position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; overflow: scroll; margin-right: -17px; margin-bottom: -17px;">'
			+'                        <table class="ty04">'
			+'                            <tbody>'
			+'                                <tr>'
			+'                                    <td class="lAlign">2018.01.15 13:03</td>'
			+'                                    <td class="cAlign"><strong>BTC</strong></td>'
			+'                                    <td class="cAlign up">입금</td>'
			+'                                    <td><strong>0.00015797 <i>BTC</i></strong></td>'
			+'                                    <td><strong>19,470,000 <i>KRW</i></strong></td>'
			+'                                    <td><strong>3,076 <i>KRW</i></strong></td>'
			+'                                </tr>'
			+'                                <tr>'
			+'                                    <td class="lAlign">2017.12.30 17:39</td>'
			+'                                    <td class="cAlign"><strong>QTUM/KRW</strong></td>'
			+'                                    <td class="cAlign down">매도</td>'
			+'                                    <td><strong>4.03648000 <i>QTUM</i></strong></td>'
			+'                                    <td><strong>71,270 <i>KRW</i></strong></td>'
			+'                                    <td><strong>287,679 <i>KRW</i></strong></td>'
			+'                                </tr>'
			+'                                <tr>'
			+'                                    <td class="lAlign">2017.12.30 17:39</td>'
			+'                                    <td class="cAlign"><strong>QTUM/KRW</strong></td>'
			+'                                    <td class="cAlign up">매수</td>'
			+'                                    <td><strong>4.03648000 <i>QTUM</i></strong></td>'
			+'                                    <td><strong>71,250 <i>KRW</i></strong></td>'
			+'                                    <td><strong>287,600 <i>KRW</i></strong></td>'
			+'                                </tr>'
			+'                            </tbody>'
			+'                        </table>'
			+'                    </div>'
			+'                    <div style="position: absolute; height: 6px; right: 2px; bottom: 2px; left: 2px; border-radius: 3px;">'
			+'                        <div style="position: relative; display: block; height: 100%; cursor: pointer; border-radius: inherit; background-color: rgba(0, 0, 0, 0.2); width: 0px;"></div>'
			+'                    </div>'
			+'                    <div style="position: absolute; width: 6px; right: 2px; bottom: 2px; top: 2px; border-radius: 3px;">'
			+'                    </div>'
			+'                </div>'
			+'            </div>'
			+'        </div>'
			+'</center>'
		},
		d_w_charge:()=>{
			return'<div id="root">'
			+'    <div class="">'
			+'      <div class="">'
			+'        <div class="mainB">'
			+'          <section class="ty01">'
			+'            <div class="halfB">'
			+'              <div class="leftB sizeUp sgdB">'
			+'                <article>'
			+'                  <div class="scrollB">'
			+'                    <div'
			+'                      style="position: relative; overflow: hidden; width: 100%; height: 870px;">'
			+'                      <div'
			+'                        style="position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; overflow: scroll; margin-right: -17px; margin-bottom: -17px;">'
			+'                        <span class="totalB"><strong>총 보유자산</strong>'
			+'                          <p> 0 <i>KRW</i></p>'
			+'						  </span>'
			+'                        <table class="ty05 highlight">'
			+'                          <colgroup>'
			+'                            <col width="190">'
			+'                            <col width="160">'
			+'                            <col width="210">'
			+'                          </colgroup>'
			+'                          <thead>'
			+'                            <tr>'
			+'                              <th style="text-align:center;">코인명</th>'
			+'                              <th style="text-align:center;">보유비중</th>'
			+'                              <th style="text-align:center;">보유수량(평가금액)</th>'
			+'                            </tr>'
			+'                          </thead>'
			+'                          <tbody>'
			+'                            <tr id="won" class="on">'
			+'                              <td>'
			+'                                <em class="logo" style="background: url(&quot;https://static.upbit.com/logos/KRW.png&quot;) 0px 0px / cover no-repeat;">-</em>'
			+'                                <a href="#" class="tit"><strong>원화</strong><i>KRW</i></a></td>'
			+'                              <td class="bar"><p align = "right">0.00%</p></td>'
			+'                              <td class="rAlign"><strong>0 <i>KRW</i></strong></td>'
			+'                            </tr>'
			+'                            <tr id="oncecoin" class="">'
			+'                              <td>'
			+'                                <em class="logo" style="background: url(&quot;/web/resources/img/logo3.png&quot;) 0px 0px / cover no-repeat;">-</em>'
			+'                                <a href="#" class="tit"><strong>원스코인</strong><i>ONCE</i></a></td>'
			+'                              <td class="bar"><p align = "right">0.00%</p></td>'
			+'                              <td class="rAlign"><strong>0 <i>ONCE</i></strong>'
			+'                                <p>0 <i>KRW</i></p>'
			+'                              </td>'
			+'                            </tr>'
			+'                          </tbody>'
			+'                        </table>'
			+'                      </div>'
			+'                      <div'
			+'                        style="position: absolute; height: 6px; right: 2px; bottom: 2px; left: 2px; border-radius: 3px;">'
			+'                        <div'
			+'                          style="position: relative; display: block; height: 100%; cursor: pointer; border-radius: inherit; background-color: rgba(0, 0, 0, 0.2); width: 0px;"></div>'
			+'                      </div>'
			+'                      <div'
			+'                        style="position: absolute; width: 6px; right: 2px; bottom: 2px; top: 2px; border-radius: 3px;">'
			+'                      </div>'
			+'                    </div>'
			+'                  </div>'
			+'                </article>'
			+'              </div>'
			+'              <div class="rightB sizeUp sgdB">'
			+'                <article>'
			+'                  <span class="titB"><strong>KRW 입출금</strong><a href="#"'
			+'                    class="refresh" title="새로고침">새로고침</a></span><span class="dlB"><dl'
			+'                      class="bg">'
			+'                      <dt class="first">보유금액</dt>'
			+'                      <dd id="h_money" class="first">'
			+'                        <strong>0 <i>KRW</i></strong>'
			+'                      </dd>'
			+'                    </dl></span><span class="tabB"><ul>'
			+'                      <li><a class="on" title="KRW충전">KRW충전</a></li>'
			+'                      <li><a class="" title="출금신청">출금신청</a></li>'
			+'                      <li><a class="" title="입출금내역">입출금내역</a></li>'
			+'                    </ul></span>'
			+'                  <div class="TabArea BgGrey KRW">'
			+'                    <span class="btnB"><em>KRW 입금(충전)을 위해 전용 계좌가'
			+'                        필요합니다.</em><a id="acc" class="btn" title="전용 계좌 만들기"'
			+'                      style="padding-top:1px;">전용 계좌 만들기</a></span><span'
			+'                      class="listB" style="height: 431px;"><strong><i>!</i>KRW'
			+'                        입출금 유의사항</strong>'
			+'                      <ul>'
			+'                        <li>KRW포인트 충전을 위한 전용번호는 <em>실명확인 입출금 계좌 인증 후</em> 발급'
			+'                          가능합니다.'
			+'                        </li>'
			+'                      </ul></span>'
			+'                  </div>'
			+'                </article>'
			+'              </div>'
			+'            </div>'
			+'          </section>'
			+'        </div>'
			+'      </div>'
			+'    </div>'
			+'  </div>'
		},
		d_w_krw:()=>{
			return '<span class="btnB">'
			+'          <em>KRW 입금(충전)을 위해 전용 계좌가 필요합니다.</em>'
			+'             <a id="acc" class="btn" title="전용 계좌 만들기" style="padding-top:1px;">전용 계좌 만들기</a>'
			+'      </span>'
			+'      <span class="listB" style="height: 431px;">'
			+'          <strong><i>!</i>KRW 입출금 유의사항</strong>'
			+'             <ul>'
			+'                <li>KRW포인트 충전을 위한 전용번호는 <em>실명확인 입출금 계좌 인증 후</em> 발급  가능합니다.</li>'
			+'             </ul>'
			+'      </span>'
		},
		d_w_application:()=>{
			return  '<span class="dlB"><div class="ListValue">'
			            +'<dl>'
			            +'<dt>출금가능</dt>'
			            +'<dd>'
			                +'0 <em>KRW</em>'
			            +'</dd>'
			        +'</dl>'
			        +'<dl>'
			            +'<dt class="incDtBt">1회 출금한도</dt>'
			            +'<dd class="incDtBt">'
			                +'50,000,000 <em>KRW</em>'
			            +'</dd>'
			        +'</dl>'
			        +'<dl>'
			            +'<dt class="incDtBt">'
			                +'1일 출금한도 <a class="btn" title="한도안내"'
			                    +'href="/service_center/guide?status=deposit_withdraw">한도안내</a>'
			            +'</dt>'
			            +'<dd class="incDtBt">'
			                +'200,000,000 <span>남음</span>'
			            +'</dd>'
			        +'</dl>'
			    +'</div>'
			    +'<dl class="inputB">'
			        +'<dt>출금계좌</dt>'
			        +'<dd>'
			            +'<select><option value="80********8805">국민은행'
			                    +'80********8805</option></select>'
			        +'</dd>'
			        +'<dt>출금금액(KRW)</dt>'
			        +'<dd class="addr">'
			            +'<input type="text" placeholder="최소 5,000 KRW" value=""'
			                +'style="color: rgb(153, 153, 153);"><a href="#" title="전액">전액</a>'
			        +'</dd>'
			    +'</dl>'
			    +'<dl class="ty01">'
			        +'<dt style="width: 40%;">출금수수료(부가세 포함)</dt>'
			        +'<dd style="width: 60%;">'
			            +'<strong>1,000 <i>KRW</i></strong>'
			        +'</dd>'
			        +'<dt>총출금(수수료포함)</dt>'
			        +'<dd class="total">'
			            +'<strong>1,000 <i>KRW</i></strong>'
			        +'</dd>'
			    +'</dl></span><span class="listB btNone" style="height: 297px;"><ul>'
			        +'<li>타인의 지시나 요청 등에 의해 본인 명의의 업비트 계정을 타인에게 대여 시 법적 처벌 대상이 될 수'
			            +'있습니다.</li>'
			        +'<li>실명 인증된 계정을 타인에게 대여하는 경우 개인정보 노출 위험에 처할 수 있습니다.</li>'
			        +'<li>은행 점검시간(매일 23:00~02:00)에는 출금이 불가능합니다.</li>'
			        +'<li>부정거래가 의심될 경우 출금이 제한될 수 있습니다.</li>'
			    +'</ul>'
			    +'<a href="#" class="btn1" title="출금신청">출금신청</a></span>'
		},
		d_w_trx:()=>{
			return  '<span class="statementB">'
		    +'<div class="f_clear">'
	        +'<div class="selectB">'
	            +'<a href="#" class="select">전체</a>'
	        +'</div>'
	    +'</div>'
	    +'<div class="scrollB" style="height: 607px;">'
	        +'<div style="position: relative; overflow: hidden; width: 100%; height: 607px;">'
	            +'<div style="position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; overflow: scroll; margin-right: -17px; margin-bottom: -17px;">'
	                +'<table class="ty06 highlight">'
	                    +'<colgroup>'
	                        +'<col width="50">'
	                        +'<col width="*">'
	                        +'<col width="50">'
	                        +'<col width="80">'
	                        +'<col width="90">'
	                    +'</colgroup>'
	                    +'<tbody>'
	                        +'<tr>'
	                            +'<td class="down">출금</td>'
	                            +'<td class="rAlign">'
	                                +'<strong>286,536 <i>KRW</i></strong>'
	                            +'</td>'
	                            +'<td class="cAlign"></td>'
	                            +'<td class="cAlign">출금완료</td>'
	                            +'<td class="rAlign">2017.12.30<br>17:43</td>'
	                        +'</tr>'
	                        +'<tr>'
	                            +'<td class="up">입금</td><td class="rAlign">'
	                                +'<strong>200,000 <i>KRW</i></strong>'
	                            +'</td>'
	                            +'<td class="cAlign">박정우</td>'
	                            +'<td class="cAlign">입금완료</td>'
	                            +'<td class="rAlign">2017.12.21<br>14:08</td>'
	                        +'</tr>'
	                        +'<tr>'
	                            +'<td class="up">입금</td>'
	                            +'<td class="rAlign">'
	                                +'<strong>200,000 <i>KRW</i></strong>'
	                            +'</td>'
	                            +'<td class="cAlign">박정우</td>'
	                            +'<td class="cAlign">입금완료</td>'
	                            +'<td class="rAlign">2017.12.01<br>22:24</td>'
	                        +'</tr>'
	                    +'</tbody>'
	                +'</table>'
	            +'</div>'
	            +'<div style="position: absolute; height: 6px; right: 2px; bottom: 2px; left: 2px; border-radius: 3px;">'
	                +'<div style="position: relative; display: block; height: 100%; cursor: pointer; border-radius: inherit; background-color: rgba(0, 0, 0, 0.2); width: 0px;"></div>'
	            +'</div>'
	            +'<div style="position: absolute; width: 6px; right: 2px; bottom: 2px; top: 2px; border-radius: 3px;">'
	                +'<div style="position: relative; display: block; width: 100%; cursor: pointer; border-radius: inherit; background-color: rgba(0, 0, 0, 0.2); height: 0px;"></div>'
	            +'</div>'
	        +'</div>'
	    +'</div>'
	    +'<div class="txtB">'
	        +'<p>* 전체 입출금 내역은 <strong><a href="/investments/history"> 거래내역</a></strong> 화면에서 확인 가능합니다.</p>'
	    +'</div>'
	+'</span>'
		},
		kakao_login:()=>{
			return '<div id="root">'
			+'	<div class="">'
			+'		<div id="checkVerifMethodModal">'
			+'			<div></div>'
			+'		</div>'
			+'		<div id="QuoteOrderConfirmPopup"></div>'
			+'		<div class="">'
			+'			<div>'
			+'				<div class="eventMargin"></div>'
			+'				<section class="loginB">'
			+'					<article>'
			+'						<h2 class="logo">UPbit</h2>'
			+'							<img'
			+'							src="//mud-kage.kakao.com/14/dn/btqbjxsO6vP/KPiGpdnsubSq3a0PHEGUK1/o.jpg"'
			+'							width="380" id="custom-login-btn" style="cursor:pointer"/>'
			+'						<div class="chkBox">'
			+'							<a href="#">checkbox</a><label for="">로그인 상태 유지</label>'
			+'						</div>'
			+'						<ul class="listB">'
			+'							<li>카카오계정으로 간편하고 안전하게 로그인(회원가입)할 수 있습니다.</li>'
			+'							<li>카카오계정이 기억나지 않으시나요?<a href="#" class="btnTxt"'
			+'								title="확인방법">확인방법</a></li>'
			+'						</ul>'
			+'					</article>'
			+'				</section>'
			+'			</div>'
			+'		</div>'
			+'	</div>'
			+'</div>'
		},
		navi:()=>{
			return '<header class="" style="z-index: 100;">'
						+'<section>'
						+'<h1>'
							+'<a title="UpBit"">UpBit</a>'
						+'</h1>'
						+'<nav>'
							+'<a style="cursor:pointer" class="" id="ngh" title="거래소">거래소</a>'
							+'<a style="cursor:pointer" class="" id="ksa_d" title="입출금">입출금</a>'
							+'<a style="cursor:pointer" class="" id="ksa_i" title="투자내역">투자내역</a>'
							+'<a style="cursor:pointer" class="" id="kth" title="코인동향">코인동향</a>'
							+'<a style="cursor:pointer" class="" id="kth2" title="고객센터">고객센터</a>'
						+'</nav>'
						+'<ul class="tnb">'
							+'<li><a style="cursor:pointer" id="ksa" title="로그인">로그인</a></li>'
							+'<li><a style="cursor:pointer" title="회원가입">회원가입</a></li>'
						+'</ul>'
					+'</section>'
				+'</header>'
		}		
};
